<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TYSS-Chaithra" failures="1" tests="1" name="runner.RunnerIO" time="14.062" errors="0" timestamp="2022-03-30T15:38:44 IST" skipped="0">
  <testcase classname="runner.RunnerIO" name="runScenario" time="14.062">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at stepDefinitions.DataDrivenTest.click_on_create_organization_lookm_up_image(DataDrivenTest.java:72)
at âœ½.Click on create organization lookm up image(file:///D:/MavenProjects/Practice.BDD/./src/test/java/features/DataDriven.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.RunnerIO -->
